Refactoring/491 cleanup datascience flavors
exasol/script-languages pull request #267
Opened 2022-02-15 11:29 UTC by tkilias

2022-02-16 09:53 UTC, tomuben approved these changes

2022-02-16 09:53 UTC, tomuben commented
Only need to update the GBuild triggers.

2022-02-16 09:55 UTC, tomuben requested changes
What about the python-3.6-data-science-cude-EXASOL-6.2.0?

2022-02-18 11:14 UTC, tomuben approved these changes

2022-02-18 11:25 UTC, tkilias reviewed
Approved, but I can click approve, because I created the PR

2022-02-18 11:28 UTC, merged