#147: Add tests for loading jvm owned native libs, like libnet or libzip
exasol/script-languages pull request #287
Opened 2022-05-09 13:49 UTC by tomuben

2022-05-09 15:33 UTC, kaklakariada requested changes

2022-05-09 15:33 UTC, kaklakariada commented on tests/test/java/jvm_owned_native_libs.py
> +                    ctx.emit(jvmName);
```suggestion
                    final String networkInterface = NetworkInterface.getNetworkInterfaces().nextElement().getName();
                    ctx.emit(networkInterface);
```

2022-05-09 16:40 UTC, tomuben commented on tests/test/java/jvm_owned_native_libs.py
> +                    ctx.emit(jvmName);
Good catch! Fixed it.

2022-05-09 16:52 UTC, tkilias approved these changes

2022-05-10 04:40 UTC, kaklakariada approved these changes

2022-05-10 11:18 UTC, merged