#950 refactored options line parser
exasol/script-languages pull request #445
Opened 2024-08-26 14:27 UTC by tomuben

related to https://github.com/exasol/script-languages-release/issues/950

2024-08-27 11:46 UTC, tkilias requested changes

2024-08-29 13:44 UTC, tomuben commented on .github/workflows/check_bazel_tests.yml
> +        export USE_BAZEL_VERSION=7.2.1
Done

2024-08-29 13:47 UTC, tomuben commented on exaudfclient/base/javacontainer/test/cpp/javacontainer_test.cc
Member variable `m_jarPaths` was removed from class `JavaVMImpl`
The test does not loose any checks, as the jar path is still validated by checking `m_classpath` (see line 15)

2024-09-02 13:43 UTC, tomuben commented on exaudfclient/base/javacontainer/script_options/scriptoptionlinesconverter.cc
Any suggestion?

2024-09-03 16:37 UTC, tkilias commented on exaudfclient/base/javacontainer/script_options/scriptoptionlinesconverter.cc
underscore and maybe remove common prefix

2024-09-04 16:11 UTC, tomuben commented on exaudfclient/base/javacontainer/script_options/scriptoptionlinesconverter.cc
Done

2024-09-05 12:07 UTC, tkilias commented on exaudfclient/base/javacontainer/script_options/BUILD
> +    name = "java_scriptoptionlines",
i think, this could also benefit from _

2024-09-05 12:07 UTC, tkilias commented on exaudfclient/base/javacontainer/script_options/BUILD
> +    deps = ["//base/script_options_parser:scriptoptionlinesparser", "//base/exaudflib:header", "//base/exaudflib:exaudflib-deps"],
i think, scriptoptionlinesparser could also benefit from _

2024-09-05 12:12 UTC, tkilias commented on exaudfclient/base/javacontainer/script_options/parser_legacy.h
> +        void findExternalJarPaths(std::string & src_scriptCode,
Might it actually better, if the script code goes only once in the parser, and these functions are only for extracting the information? This way, we could parse in the new parser the code once and then only work on the extracted information.

2024-09-05 12:55 UTC, tomuben commented on exaudfclient/base/javacontainer/script_options/BUILD
> +    deps = ["//base/script_options_parser:scriptoptionlinesparser", "//base/exaudflib:header", "//base/exaudflib:exaudflib-deps"],
Done

2024-09-05 12:57 UTC, tkilias approved these changes

2024-09-05 15:17 UTC, merged