#1036: Added pytorch and numba integration test compatible with CPU only VM
exasol/script-languages pull request #485
Opened 2024-12-09 16:27 UTC by tomuben

related https://github.com/exasol/script-languages-release/issues/1036

2025-01-03 13:22 UTC, tkilias commented on test_container/tests/test/python3-cuda-flavor/pytorch.py
> +        self.assertIn('Mean Squared Error', row[0])
I would assert if the loss is not NaN, this could hint to something is broken, if it worked before

2025-01-03 14:58 UTC, kaklakariada requested changes

2025-01-03 14:58 UTC, kaklakariada commented on test_container/tests/test/python3-cuda-flavor/numba.py
> +        row = self.query("SELECT numbabasic.test_numba(10000);")[0]
Is it necessary to verify the returned value?

2025-01-03 15:26 UTC, tomuben commented on test_container/tests/test/python3-cuda-flavor/numba.py
> +        row = self.query("SELECT numbabasic.test_numba(10000);")[0]
I think not. The return value is some random number.  If there is any problem, an exception is thrown and this breaks the test.

2025-01-03 17:34 UTC, tkilias commented on test_container/tests/test/python3-cuda-flavor/pytorch.py
> +        self.assertFalse(math.isnan(row[0]))
I think, NaN is transformed to NULL in the DB

2025-01-03 17:35 UTC, tkilias commented on test_container/tests/test/python3-cuda-flavor/numba.py
> +        row = self.query("SELECT numbabasic.test_numba(10000);")[0]
In that case your are assert should be , did we get a row back

2025-01-07 11:06 UTC, tomuben commented on test_container/tests/test/python3-cuda-flavor/pytorch.py
> +        self.assertFalse(math.isnan(row[0]))
Appearantly the build failed when fetching micromamba. Running the test locally , the assert is correct.

2025-01-07 14:06 UTC, tomuben commented on test_container/tests/test/python3-cuda-flavor/numba.py
> +        row = self.query("SELECT numbabasic.test_numba(10000);")[0]
Added an assert for the resulting row

2025-01-07 14:08 UTC, kaklakariada approved these changes

2025-01-07 14:17 UTC, tkilias approved these changes

2025-01-07 14:25 UTC, merged